import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";

import StoreProvider from "./StoreProvider";
import Footer from "@/components/footer";

import "./globals.css";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "The Next CRM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <ThemeProvider attribute="class" defaultTheme="light">
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
