import type { Metadata } from "next";

import StoreProvider from "./StoreProvider";
// import Header from "@/components/header";
import Footer from "@/components/footer";

import "./globals.css";

export const metadata: Metadata = {
  title: "The Next CRM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          {/* <Header /> */}
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
